= Integration test plugin for mill plugins
:version: 0.2.0
:exampleMillVersion: 0.6.1
:toc:
:toc-placement: preamble

ifdef::env-github[]
image:https://travis-ci.org/lefou/mill-integrationtest.svg?branch=master["Travis CI Build Status", link="https://travis-ci.org/lefou/mill-integrationtest"]
endif::[]

Integration testing for mill plugins.

== Quickstart

We assume, you have a mill plugin named `mill-demo`

[source,scala]
----
// build.sc
import mill._, mill.scalalib._
object demo extends ScalaModule with PublishModule {
  // ...
}
----

Add an new test sub-project, e.g. `itest`.

[source,scala,subs="verbatim,attributes"]
----
import $ivy.`de.tototec::de.tobiasroeser.mill.integrationtest:{version}`
import de.tobiasroeser.mill.integrationtest._

object itest extends MillIntegrationTestModule {

  def millTestVersion = "{exampleMillVersion}"

  def pluginsUnderTest = Seq(demo)

}
----

Your project should now look similar to this:

----
.
+-- demo/
|   +-- src/
|
+-- itest/
    +-- src/
        +-- 01-first-test/
        |   +-- build.sc
        |   +-- src/
        |
        +-- 02-second-test/
            +-- build.sc
----

As the buildfiles `build.sc` in your test cases typically want to access the locally built plugin(s),
the plugins publishes all plugins referenced under `pluginsUnderTest` to a temporary ivy repository, just before the test is executed.
The mill version used in the integration test then used that temporary ivy repository.

Instead of referring to your plugin with `import $ivy.'your::plugin:version'`,
you can use the following line instead, which ensures you will use the correct locally build plugins.

[source,scala]
----
// build.sc
import $exec.plugins
----

Effectively, at execution time, this line gets replaced by the content of `plugins.sc`, a file which was generated just before the test started to execute.

== Configuration and Targets

The mill-integrationtest plugin provides the following targets.

.Mandatory configuration
* `def millTestVersion: T[String]`
  The mill version used for executing the test cases.
  Used by `downloadMillTestVersion` to automatically download.

* `def pluginsUnderTest: Seq[PublishModule]` -
  The plugins used in the integration test.
  You should at least add your plugin under test here.
  You can also add additional libraries, e.g. those that assist you in the test result validation (e.g. a local test support project).
  The defined modules will be published into a temporary ivy repository before the tests are executed.
  In your test `build.sc` file, instead of the typical `import $ivy.` line,
  you should use `import $exec.plugins` to include all plugins that are defined here.

.Optional configuration
* `def sources: Sources` -
  Locations where integration tests are located.
  Each integration test is a sub-directory, containing a complete test mill project.

* `def testCases: T[Seq[PathRef]]` -
  The directories each representing a mill test case.
  Derived from `sources`.

* `def testTargets: T[Seq[String]]` -
  The targets which are called to test the project.
  Defaults to `verify`, which should implement test result validation.

* `def downloadMillTestVersion: T[PathRef]` -
  Download the mill version as defined by `millTestVersion`.
  Override this, if you need to use a custom built mill version.
  Returns the `PathRef` to the mill executable (must have the executable flag).

* `def temporaryIvyModules: Seq[PublishModule]` -
  Additional modules you need in the temporary ivy repository, but not in the resulting mill build classpath.
  The defined modules will be published into a temporary ivy repository before the tests are executed.


.Commands / Action Targets
* `def test(): Command[Unit]` -
  Run the integration tests.

* `def testCached: T[Unit]` -
  Run the integration tests (same as `test`), but only if any input has changed since the last run.

== License

This project is published under the https://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0].


== Version Compatibility Matrix

Mill is still in active development, and has no stable API yet.
Hence, not all mill-integrationtest versions work with every mill version.

The following table shows a matrix of compatible mill and mill-integrationtest versions.

.Version Compatibility Matrix
[options="header"]
|===
| mill-integrationtest | mill
| 0.2.0 | 0.5.7
| 0.1.2 | 0.5.7
| 0.1.1 | 0.5.7
| 0.1.0 | 0.3.6 - 0.5.3
|===

== Changelog

=== master

* Bumped Mill API to 0.6.0

=== mill-integrationtest 0.2.0 - 2020-02-27

* Added support to run selective tests
* Targets `test` and `testCached` no return the test result
* new target `testCachedArgs` to control args feeded to testCachedArgs
* Test executor now generated a mill script which allows you to manually invoke mill in
  a test destination directory
* New target `testInvocations` providing much finer control over executed targets and their
  expected exit value

=== mill-integrationtest 0.1.2 - 2020-02-18

* New target `temporaryIvyModulesDetails`
* New target `testCached`

=== mill-integrationtest 0.1.1 - 2020-01-08

* Version bump mill API to 0.5.7

=== mill-integrationtest 0.1.0 - 2019-02-21

* Initial public release
