on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

# cancel older runs of a pull request;
# this will not cancel anything for normal git pushes
concurrency:
  group: cancel-old-pr-runs-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [8, 11, 17]
    runs-on: ${{ matrix.os }}
    # continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - run: ./millw -i -k -d __.testCached + __.scoverage.xmlReport + __.publishLocal testRepo
        if: matrix.os != 'windows-latest'
      - run: .\millw.bat -i -k -d __.testCached + __.scoverage.xmlReport + __.publishLocal testRepo
        if: matrix.os == 'windows-latest'

      - name: Upload scoverage reports to codecov.io
        uses: codecov/codecov-action@v5
        with:
          files: ./out/integrationtest/0.11/scoverage/xmlReport.dest/scoverage.xml,./out/integrationtest/0.10/scoverage/xmlReport.dest/scoverage.xml,./out/integrationtest/0.9/scoverage/xmlReport.dest/scoverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

  publish:
    if: github.repository == 'lefou/mill-integrationtest' && github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Setup GPG secrets for publish
        run: |
          gpg --version
          cat <(echo "${{ secrets.GPG_SECRET_KEY }}") | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Maven Central
        run: MILL_VERSION="0.12.14" ./millw -i --import "ivy:com.lihaoyi::mill-contrib-sonatypecentral:" mill.contrib.sonatypecentral.SonatypeCentralPublishModule/publishAll --publishArtifacts __.publishArtifacts
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASS }}
          # MILL_PGP_SECRET_BASE64: ${{ secrets.GPG_SECRET_KEY }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
