on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

# cancel older runs of a pull request;
# this will not cancel anything for normal git pushes
concurrency:
  group: cancel-old-pr-runs-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [8, 11, 17]
    runs-on: ${{ matrix.os }}
    # continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - run: ./millw -i -k -d __.testCached + __.scoverage.xmlReport + __.publishLocal testRepo
        if: matrix.os != 'windows-latest'
      - run: .\millw.bat -i -k -d __.testCached + __.scoverage.xmlReport + __.publishLocal testRepo
        if: matrix.os == 'windows-latest'

      - name: Upload scoverage reports to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: ./out/integrationtest/0.11.0-M8/scoverage/xmlReport.dest/scoverage.xml,./out/integrationtest/0.10/scoverage/xmlReport.dest/scoverage.xml,./out/integrationtest/0.9/scoverage/xmlReport.dest/scoverage.xml
        continue-on-error: true

  publish:
    if: github.repository == 'lefou/mill-integrationtest' && github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      - name: Setup GPG secrets for publish
        run: |
          gpg --version
          cat <(echo "${{ secrets.GPG_SECRET_KEY }}") | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Maven Central
        run: ./millw -i mill.scalalib.PublishModule/publishAll --sonatypeCreds "${{ secrets.SONATYPE_CREDS }}" --gpgArgs "--passphrase=${{ secrets.GPG_SECRET_KEY_PASS }},--batch,--yes,-a,-b,--pinentry-mode,loopback" --publishArtifacts __.publishArtifacts --readTimeout 600000 --awaitTimeout 600000 --release true --signed true
